### PR TITLE
feat: Documentation, Organisation, Cleanup

### PR DESCRIPTION
**Pull request by chris-hatton**
### What

- Amend documentation, including Quick-Start steps
- Organise initial v0 search code into matching v0 API package
- Remove unnecessary .idea and .obsidian metadata folders

### Reviewing

💡 I recommend [browsing the source branch in GitHub](https://github.com/chris-hatton/openfoodfacts-kotlin/tree/improvements) to review the documentation changes.

### CODE REVIEW

**Comment by VaiTon** [comment]
@chris-hatton as a user of the API, will I be exposed to v0, v1, v2 or we do that only internally?

**Comment by chris-hatton** [comment]
@VaiTon Yes it was my intention to expose the v0, v1, v2.  The reason is; I found it personally confusing as a new developer to OpenFoodFacts, to encounter conflicting/redundant documentation for Search API's.  Although I have a better understanding now; I felt it would be more explicit for new developers up-front to see that there is this progression of API versions.  Also; allowing for v0, v1, v2 packages enables clients for each of these to co-exist in the same library until such time as one is fully retired.

That said; it's more important to align with OpenFoodFacts direction on these matters; if you would tell me you'd rather transition to 'latest version' of all features ASAP and refrain from referring to v0, v1, v2 etc. then that is a reasonable approach I can also support.  Please kindly advise.

**Comment by teolemon** [comment]
- The new rage is V3, and there's an OpenAPI documentation which might be able to auto-generate Kotlin code
- https://openfoodfacts.github.io/openfoodfacts-server/reference/api/

**Comment by VaiTon** [comment]
@chris-hatton I think the best course of action here is to deal only internally with API versions and expose a clean SDK to end-users. 

This way we take the burden of making the SDK work and we don't push it to end users, in a way that deprecating exposed methods should be something that we only consider as a last option.

**Comment by chris-hatton** [comment]
@VaiTon @teolemon I'm picking this back up now after some hiatus; have updated the source to newer dependencie. Will look to remove 'version' packages and present a single Kotlin API backed by the v3 REST API.

**Comment by VaiTon** [comment]
Ok @chris-hatton, let me know when you get to push it, so that I can start using it from the Android app.

**Comment by teolemon** [comment]
@chris-hatton Is it ok to merge this PR ?
With Kotlin Multiplatform being all the rage right now, it would be great to have our SDK in fit shape :-)

**Comment by teolemon** [comment]
@VaiTon do you think it's mergeable ?

**Comment by teolemon** [comment]
i'm going to merge

**Comment by teolemon** [comment]
@chris-hatton @VaiTon

**Pull request merged**
