### PR TITLE
Initial OpenFoodFacts Kotlin/Multiplatform SDK project

### PR DESCRIPTION
**Pull request by chris-hatton**
### What

Initial OpenFoodFacts Kotlin/Multiplatform SDK project featuring:

- Library project targeting Android, iOS and Desktop that performs a product query against v0 API
- Example 'Test Apps' for Android, iOS and Desktop that demonstrate using the Library, along with Compose/Multiplatform
- Composite workspace project to assist with further development/maintenance work
- Initial documentation

### Screenshot
To be added

### Why is this a draft?

I want to provide some visibility of this largely complete delivery to invite feedback; while still working on:
- Tidying up code
- Improving documentation
- Implementing a GitHub Actions(?) CI pipeline

### CODE REVIEW

**Comment by teolemon** [comment]
I've added @VaiTon to the PR, who's much more Kotlin knowledgeable than me

**Comment by VaiTon** [comment]
Hey @chris-hatton! Thank you for your work! Despite thinking that this is not the best place for a code review, as we can merge and then work from there, I have two questions:
- What is .obsidian?
- Why do we need a Gradle Composite here?

**Comment by chris-hatton** [comment]
> * What is .obsidian?

It's a metadata folder for the [Obsidian Markdown/Documentation browser](https://obsidian.md).  Obsidian provides enhanced documentation browsing using a super-set of Markdown.  It is a preferred viewer/editor for this projects documentation, although others will work fine too.

> * Why do we need a Gradle Composite here?

This submission includes both a **Library** project and a **Development App** project (to test-drive the **Library**).
For cleanliness, these two projects are entirely separate.  The **Development App** depends on the **Library** of course, but it does so via a standard Maven artifact dependency, without including the **Library** project directly.

However, it can be useful for maintainers to run both projects in the same IDE workspace as though they are one project.
Gradle Composite enables this type of workflow, and so a Composite project is provided here to 'loosely couple' the Library and Development App when it's desirable to work on them simultaneously.

This is talked about in the top-level `README.md`.

**Comment by VaiTon** [comment]
Thank you for your work @chris-hatton! 🎉

**Pull request merged**
